/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PharmaceuticalProduct = IDL.Record({
  'imageUrls' : IDL.Vec(IDL.Text),
  'packSize' : IDL.Text,
  'dosage' : IDL.Text,
  'form' : IDL.Text,
  'name' : IDL.Text,
  'priceEurope' : IDL.Float64,
  'priceUk' : IDL.Float64,
  'strength' : IDL.Text,
  'units' : IDL.Nat,
  'manufacturedBy' : IDL.Text,
  'brand' : IDL.Text,
  'packaging' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ShippingAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'apartment' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'streetAddress' : IDL.Text,
  'firstName' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'status' : IDL.Text,
  'total' : IDL.Float64,
  'createdAt' : Time,
  'customerUsername' : IDL.Text,
  'shipping' : IDL.Float64,
  'email' : IDL.Text,
  'orderId' : IDL.Text,
  'shippingAddress' : ShippingAddress,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'registrationDate' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([PharmaceuticalProduct], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(PharmaceuticalProduct)], ['query']),
  'getAllUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [PharmaceuticalProduct], ['query']),
  'getProductsByBrand' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PharmaceuticalProduct)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        ShippingAddress,
        IDL.Vec(OrderItem),
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Text],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([IDL.Text, PharmaceuticalProduct], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PharmaceuticalProduct = IDL.Record({
    'imageUrls' : IDL.Vec(IDL.Text),
    'packSize' : IDL.Text,
    'dosage' : IDL.Text,
    'form' : IDL.Text,
    'name' : IDL.Text,
    'priceEurope' : IDL.Float64,
    'priceUk' : IDL.Float64,
    'strength' : IDL.Text,
    'units' : IDL.Nat,
    'manufacturedBy' : IDL.Text,
    'brand' : IDL.Text,
    'packaging' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ShippingAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'apartment' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'streetAddress' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'status' : IDL.Text,
    'total' : IDL.Float64,
    'createdAt' : Time,
    'customerUsername' : IDL.Text,
    'shipping' : IDL.Float64,
    'email' : IDL.Text,
    'orderId' : IDL.Text,
    'shippingAddress' : ShippingAddress,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'registrationDate' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([PharmaceuticalProduct], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func(
        [],
        [IDL.Vec(PharmaceuticalProduct)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [PharmaceuticalProduct], ['query']),
    'getProductsByBrand' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PharmaceuticalProduct)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          ShippingAddress,
          IDL.Vec(OrderItem),
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Text],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([IDL.Text, PharmaceuticalProduct], [], []),
  });
};

export const init = ({ IDL }) => { return []; };