/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PricingRegion = IDL.Variant({
  'uk' : IDL.Float64,
  'europe' : IDL.Float64,
});
export const PharmaceuticalProduct = IDL.Record({
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'units' : IDL.Nat,
  'brand' : IDL.Text,
  'price' : PricingRegion,
  'packaging' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(PharmaceuticalProduct)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [PharmaceuticalProduct], ['query']),
  'getProductsByBrand' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PharmaceuticalProduct)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PricingRegion = IDL.Variant({
    'uk' : IDL.Float64,
    'europe' : IDL.Float64,
  });
  const PharmaceuticalProduct = IDL.Record({
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'units' : IDL.Nat,
    'brand' : IDL.Text,
    'price' : PricingRegion,
    'packaging' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'getAllProducts' : IDL.Func(
        [],
        [IDL.Vec(PharmaceuticalProduct)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [PharmaceuticalProduct], ['query']),
    'getProductsByBrand' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PharmaceuticalProduct)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };