/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'status' : string,
  'total' : number,
  'createdAt' : Time,
  'customerUsername' : string,
  'shipping' : number,
  'email' : string,
  'orderId' : string,
  'shippingAddress' : ShippingAddress,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
  'subtotal' : number,
}
export interface OrderItem {
  'productName' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface PharmaceuticalProduct {
  'dosage' : string,
  'name' : string,
  'priceEurope' : number,
  'priceUk' : number,
  'units' : bigint,
  'brand' : string,
  'packaging' : string,
}
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'apartment' : string,
  'zipCode' : string,
  'state' : string,
  'phone' : string,
  'lastName' : string,
  'streetAddress' : string,
  'firstName' : string,
}
export type Time = bigint;
export interface UserProfile { 'username' : string, 'registrationDate' : Time }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, number, number, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<PharmaceuticalProduct>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], PharmaceuticalProduct>,
  'getProductsByBrand' : ActorMethod<[string], Array<PharmaceuticalProduct>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, ShippingAddress, Array<OrderItem>, number, number, number],
    string
  >,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];